# Standards: 1.2
---
- name: Download repo key
  shell:
    cmd: curl -sSL https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
    creates: /usr/share/keyrings/1password-archive-keyring.gpg
  tags:
    - onepassword

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    filename: 1password
    update_cache: True
    state: present
  tags:
    - onepassword

- name: Install required packages
  loop:
    - 1password
  package:
    name: "{{ item }}"
    state: present
  tags:
    - onepassword

...
